import time
from typing import List
from collections import defaultdict


class Solution:
    def __init__(self):
        self.similarDict = defaultdict(set)

    def numSimilarGroups(self, A: List[str]) -> int:
        """Returns the count of similar string groups."""
        words = set(A)
        self.buildSimilarDict(A, len(A), len(A[0]))

        groupCount = 0
        while words:
            groupWords = set()
            bfsQueue = [words.pop()]
            while bfsQueue:
                curWord = bfsQueue[0]
                similarWords = self.similarDict[curWord].intersection(words)
                if similarWords:
                    bfsQueue.extend(similarWords)
                    words = words - similarWords
                # basic BFS operation
                groupWords.add(curWord)
                bfsQueue.remove(curWord)
            if groupWords:
                # print(groupWords)
                groupCount += 1
        return groupCount

    def buildSimilarDict(self, words: set, wordsCount:int, wordLen:int):
        if wordsCount > wordLen:
            findSimilarWords = self.findSimilarWordsA   # O(N * W^2)
        else:
            findSimilarWords = self.findSimilarWordsB   # O(N^2 * W)
        
        for word in words:
            # similarDict: size(len(words), len(word))
            self.similarDict[word] = findSimilarWords(word, words)

    def findSimilarWordsA(self, word: str, words: set) -> set:
        """Return all similar words of a word. O(W^2)"""
        similarWords = set()
        for i in range(len(word)):
            for j in range(i + 1, len(word)):
                similarWord = word[:i] + word[j] + word[i + 1:j] + word[
                    i] + word[j + 1:]  # replace i, j
                if similarWord in words:
                    similarWords.add(similarWord)
        return similarWords

    def findSimilarWordsB(self, curWord: str, words: set) -> set:
        """Return all similar words of a word. O(NW)"""
        similarWords = set()
        for word in words:
            if self.isSimilar(curWord, word):
                similarWords.add(word)
        return similarWords

    def isSimilar(self, wordA, wordB):
        """Returns if two words is similar(2 chars swapped). O(W)"""
        if len(wordA) != len(wordB):
            return False
        diffCount = 0
        diffChars = set()
        for i in range(len(wordA)):
            if wordA[i] != wordB[i]:
                diffCount += 1
                diffChars.add(wordA[i])
                diffChars.add(wordB[i])
        if diffCount == 2 and len(diffChars) == 2:
            return True
        return False


if __name__ == "__main__":
    # A = ["tars", "rats", "arts", "star"]
    A = [
        "jqmknamokpmtavoxvfwxvzgwrmohjuyldjfsjbftnoirbgajjciurynqivkniqyenanhkdahsjkxsiowyxenibnaodavgvkvbcexakbjuljbvmdlaavqlpihvpwaipekvuxoeqvueyqtlbftzkyzyugkzygotbkdmlgkwjwvjwjhhqzmdaqhgfxekogkvaqsdeifubvbplklsludrntmemrygxqhpvvcjeigbmwsapivrksllvdcyzuviu",
        "bmqlkudnzeviaeqvquzmbappzksbvauwxuqfpwkfvvkbeidgcmqleqevnylhxubyvjdhqkayngerithocfvjkkyudcwllguvwjhbvjopnkvxhljddjgfjryknyuiomtkmhxritjadkeixazaiuqgyjsyvyaiisfvqigfilorpkpmvlvamxvjmsvmatobhxhwjnbblzjosxsatqkpwwvalyodkrkagznbbnslvjnevodcugeggktiaemwro",
        "riellsqyeiuqzjpapwvmpqyezartjhflvjwuqkvbfjuydbitkwypnnbksjbtjbaqiuazlewvdwbxevlndxpilqgvmoyavavgaomyiokxuajyhagixcjdeisrvvakfsjknqehkhvkvmnmwjgmevqhrnkpawlstkxfvoyudaznivhgkbbdpditucrhtqehbxiagraxuikldnzlukvxfnkkjgmlksmsgoqvdmebvjgyclboomvwvfyogojucz",
        "zvqrvglckdqebxpuclgbizragbnwrwnabpqxuxadkuwdgxecmsvejibnjheqkraxssuqoywromyhhzvklkdjxiaeihimkkofdungkmskfjujkymvvvkdaygcnlymjyvvkxywzanqikplkwmephuafavyfveieobqbhjnaoyjogxgntbqsddiftihqteieomfjvgylvvoqvbjptupkzwtjnlijslbgkmiuvhlaavtvdljbpwsoulvazvarm",
        "olwrmjdvzgnsinneshaqfwqbmqezmmbvvykbdqqegntsxoyyktwbxnbqvbhaubkmgtkjqjugkaelribjeaxaciepkrbfdhjqmvnlevykdsnrvujluvaxyykuphoyoakmaxwobzpivilvtoifealvanjovtgkjlqjswrjpvfvhkvilkrtmwikigpmdkiogzqygycigaxvdvzxxpadudnudylujjhmhfkclcavavpvswjlubeioukwfhgesz",
        "ivejavaxvbmvplklwgyawesimhovskbhivsinnobrkhddetfamkhkdkoivxcajsgtxezatcfevjlbqwbkxidqyyyknkykujkiwvaovidjzmoouqnwrmpibrpmmwgnkbvnsjjfymdgyqlalnfvyicvboungbjmuuhfghtjbsuaqlzateyvregldevrkxlkuvboyepkvoxxcamgdfsjqtpguuqgaewlazvqrvuzzqjjhqilipwpxkhjvland",
        "pohyyliinotagjkbbdrdvxgkhqmvbnsjuivtjrzzjdxenbvlndnakptjzfoixifmujdbavnuwvxsgmefkjqsmcgqwpidoilulcizeojklwbsuhpaotkiileujkkrvbblyzecwyjedphjokahaaeahwqqalkqmfmfvvuvqlxtbmrvahyyidibvkvfsqxptvezxyxgnoqwahmdskuajvkogklucagggevkqanjvmvvmrsgkrvupynwweblyy",
        "ieonegohvqdijnjwziloffltzumageoynbiyureqtezkblpbdvmvbacijbwfenzdgoyvqvsyckhaoksmbkkrjmjjynskmglfvoskbwtxtaiwlkdwyabmjvhjphkuayreqhakvghmztcupximpxprqbejgxbjuhfiudwjvlsilpaegmtqvsrqanuvkvdlasvbknhrwlakxiqcvvlaajfzxvkdiagnvkdqgdyqkyuuvwupoxmiejlvgxvyon",
        "gabjzebcibeprlntvmlvhdowqsutwfcobbjyvgktwqdhbukauqlhvvxvkvfblkvckiwvkunjjiogwupmfstkrasnpgjeqawvlyzyokkveqlkqvdkjegajyzhvybrmzoippatpwfmvveoxijighkrnlgqvadjiryqmxonepkuvukgauarbwlvoamlxixinjytmbaokylauvvlgzmqhfbiycyfuedjnsqjmhsazaskenmeidgidsxdhjxxnd",
        "wdjbpfcewhuvjfqdyqeomfptuqxdtjiwwryjalbitkijkhkajglxgawkvesuydghfhxzirzgydyabooitxobgldmsfchxinipvaessorcxayxbdvvhnouqtkvbuyneywdzldhvkqsuwingpugklemgmvacrkekvpvnaulablvaumaabjvrevjovvrjtlvmifxnyneapwupvjnkmibzqvhkqbqykzavqlgkbqvljizesokmsjlmmoknjigk",
        "gkgvvevavbufeqpyllaomzscsnirdrekaxwsttyaqkerxkwajvkfyvncomhzlukenknkwcbhabhpjgvramogpiauglkxbaithsyuijrijlbkdeopjyxwiufoqupldkkzxwvqktqsqjogbbngqvmphexqyigvdnmxdkdmzujyveuksziavmnhnvtovrmdavckqbwtgbvaiflabuvdjjbqvzlidjlfynejlushwamiyvvjjmlyefgxhiwpoo",
        "kgsvaulqzodwgbgtjxhiaqgqskbbohditezlgiixzumrjdvwkedwvpazifmgxvkpbuevpbvfveykqngjrasvxrbiqbhqclevvnvnfqqtkggiwrirqtnonkknkcylvaqvjulkmsmhfslbwdvjpwmgakneuotdyjovmbvaszypvlajajjbcaauyltaewdikvnomyixmviyaapxvcmldfbjyekzjjiwkuusefuxooyhnkhkmydrxhluoljehp",
        "zwrhbdinbkaikqotbsbipdqkfmeyfjsgqbhkirvwlcvrfsuomxkekxlyjrovknyveaqxhhlxvppvsykbnpiitdwjklvteomcziqwaaelavalbpvjugdrvdovkmgwhkwqveafapojbyvjrnmsekwgukmiabtazvhqexoukqhjktojhodgclljeeuvgysalzivzyguftuxnsxayfivwzjmyaajbinlvcnxdbjdnqipyknmuvvmuujlgggmdq",
        "xhgcsxeuqvqhmegcjbqdsjvrpzvuokyzvjnqdfaajgtafbvwpebvkhmgyixolkwroodtnvmkcvtnuvejkyqtgyyjardvrpbdvasiowkjkkulomldlxnuayewupgpwozqxvlfpnanexbuiqmtjfbjkwohmxdduoxmknvvseinlkkiyyrfiluiazrajqvhvkswidspvmqbblstelabivjmemwakuahkvjzgyeialvhlqgbgjzyaihbgicfnk",
        "akyzdjdzztxvuduxkqklievwnfbozdxaojbdklpefiaawobamqezvqjpeuskgmrrlyaquftcgribbmkpdviamegektoblvevjrvvtnukmvwpgmvlakexynnsbahgvwobsejivgblljhikxduxrvacqqdkpighfhkyugkkysjlgmtmsljjosihvynmcmlcaqsnhvfjbxxeqtprquvywnydkpqvkagavwjnwyfnhaziijywohjuuovlviiob",
        "aplgbwviabkgbnqnwrxgsqwevyhaeddxdvijjtqiutkvdvnbsplsjsouipsjvhcbydopgkkonmadgmmbynvlxekownixavuyybkvufkkkfibbzvvmkbcrhkjilkergkmaywqiuhrewamzjmvzyhholhajlljvzxkedvqyeafxlhglouqpdmazikrqusvgffmzavcntyjckvvqiejgqajtwdueaixwtjqfnjenvpbrgvuaospltmuiyxool",
        "ikaiaihivqfvwqixouhzwkaidlvksgyhdnrlzyvbqzabwuvjelpnakqnevkuaalejyhbymsxlsnpqxynvvlhhikqctrswduvvvfqjmmyhoaoxwpiaqdueklgsdosnbvkbmjdmcawfregiuikbvbfjokjylkugqjxesgjigvpvwouggajtlobrmiennmxkpdoreftkokvxhjbyemlakwjgmgavdvrtbztcdbyvvzujxtzcepnfjmyalkupq",
        "ueevkksbxmxvdutenusguauvloqdzonkrkqyvrlaithgeluavkhpxqaaaoysrpezajvkmpdatuvqyksmhvapkjnmgxvuyuxjlbwkrbfvkwlqrtepbbjzyovfkqveifajygqcinbfgdeasmzjaxibliqogbvwndhfgiakygabxdhovmghqskmyvzpuivwqknmwlihnkzojpyjsjrjvkclmwinwgjljccljoeilndtbovhdxydmwbvtvifei",
        "zausjriawclxmheuujynfiabieqrvqdpibykxztgdxkboakhhimwwhvhqjipbwuglnlugrigojkynrvpffekiblduyzvanrhjgajskejsqeomuyxbgjynssnbmklejbpvkktvanqoxcuvfyeakhkdodgkqpieoitavwmavrgqxvtdjmhwpcgyvoqisbuvykebllunvvjxlyfclaqafavdtldzqewvvvoktsklnjdzmmxvabmvomzigpkjw",
        "egmbkbxacjymangbysmukgimajokpnqqdhiolyajahnzpkjeikoumvjgmafazxdkqcwzvlrdzuqvslwurtbbslecumwnmguxngvobinkkhhmwgpxawevlveejrydnivvbgkfhblijcatjjwjwadupxqsiveqtsqofpldeykjiywlarfdypiktprvqkuvuqvbvsfodqknvvlkijojzbioxheevxadzhvvamtotnaglyvyxgisublvfkhkry",
        "ieonegohvqdijnjwziloffwtzumageoynbiyureqtezkblpbdvmvbacijblfenzdgoyvqvsyckhaoksmbkkrjmjjynskmglfvoskbwtxbaiwlkdwyatmjvhjphkuayreqhakvghmztcupximpxprqbejwxbjuhfiudwjvlsilpaegmtqvsrqanuvkvdlasvbknhrglakxiqcvvlaajfzxvkdiagnvkdqgdyqkyuuvwupoxmiejlvgxvyon",
        "svarvvkgudabhnjazoiffpmqwdekdwftwkcisvkbkyusjuqglbnyuslyauqiwqmyoniexvoqivlvkbpeivvfgrwhvvajnyakskktzvdlroaevjbdxvluaianwmkdvljoebpygkjzelasobmgptyjdanvqluuqgmpxhelucxxyefvbgcktvaiztnhyoibkoqwqxdnzjjogejvwxymhmlhiurcriljnxjskjkrvztqempmpbgkfhbaigdahm",
        "kirckfiiujesbjkqbjthvamlmylartnaumuxjwaaqlwnrqqdvmanvbpgejxvdxyykofrhlngzkcwbquiiucovkjioboideggkqsnmkkdaggsavibwzfdmoluktpybvhgfxehuojbmjcivehnwvlsiekjeaukdvzwaeyyvpdmrjfxqawnajyoeqgiddsytvwyzpangvklvbjtkhvusovyohrvkbkhvjitvxxqpgslmlbmellpquzpnafxvz",
        "hadqkesxllraekarnegwjqoduaawrpokvusqcauylyvrysnlvlkqxwkxvpvpieuvvnjvjgvjtcuqdxivozitieqdjdnexhbeaclvphlaqmwmsxxjljfbfiogkkhkjtzxyvakmnofgmhuvsyabbmpjdesmbbhkzhjbfkndmyjbkkqavjvdbfgluvivgiealimwpzqsfgoivzyjunyowievipvcuytdnlrwqoatzikbbahwrmmgngkuytgok",
        "mvmbmhdqzrvxdubiajqgohcggpjmkhytvfjakjokfdvimlueplyyldarrfdinvhwjalafgcmwiwhgzxnnzaliivvgvbeqvjetuvdfasaeewklqhyivebzetgjohmotvmvbvbgvofiiezumkjdkxjknrcjopsqxrypztibqikbyrsokvoykpmyugodqkwleaxyvugakkbqjcxnwvhpxxavwdapsuinjetljwlanyqlnuaubkslvkqskubns",
        "olwrmjdvzgnsinneshaqfwqbmqezmmbvvykbdqqegntsxoyyktwbxnbqvbhaubkmgtkjqjugkaelribjeaxaciepkrbfdhjqmvnlevykdsnrvujluvaxyykuphoyoakmaxwobzpivilvtoifealvanjovtgkjlqjswrjpvfvhkvilkrtmwikigpmdkiogzvygycigaxvdvzxxpadudnudylujjhmhfkclcaqavpvswjlubeioukwfhgesz",
        "xhgcsxeuqvqhdegcjbqdsjvrpzvuokyzvjnqdfaajgtafbvwpebvkhmgyixolkwroodtnvmkcvtnuvejkyqtgyyjardvrpbdvasiowkjkkulomlmlxnuayewupgpwozqxvlfpnanexbuiqmtjfbjkwohmxdduoxmknvvseinlkkiyyrfiluiazrajqvhvkswidspvmqbblstelabivjmemwakuahkvjzgyeialvhlqgbgjzyaihbgicfnk",
        "wqijnqulcanqvuewodakbvsfxwikxoxanltjdiogybkcrvhojaqybfhlkgfejyjvzqwpivledsstlgjplkkawtavpncjvbmetvxkdgwkmbmblvhgusvlxrkboymmvjpkuwburumjainunnrprrlcvtgykqsquhdaqzekkngjgoxbvekihmiyyivzkvueehygabfvpwosikiidzjfvjxlldvjxhpqteiymhugdnamqzdveomaazsfbovaya",
        "kxbggdwqihopvldajvbmmznolsdvujoovivzmnjfyuejjdszlyhoplaainckjkyznajnznqkdvvauuyswykypfaetvrgjvsdzxiruibplgidkfawyvkfeubwhvqrgkkvfmtvjtwememqhmgaiubsxpfegakbtuxpxrojjmgrqtldmqlbkchklixispsvanhuqokbkbbgbmvqqhcywnveaytgeuyalvvvnxqoiikevlkclawewohadjrijx",
        "lyykqqzwqvgmajbzobfmrtfprnarnlveeljibbxgqwhdugknjdpqvnpkeekvdiygxppitdgvxvjqyejgkjihzdoiubsqhatlqyeakladufcwzbyzycvpcnmbuiujlzvfadhybljwiulnaamkheoojegshbdivkvasnyudukogamxbisiwvinoavwkvwyxvshirekjupkxfmvjmjsggxrkrlvvmovqbkkkmttjaaoltcnohvwfvmelquasx",
        "pinndzmotucqyalkewodvujphdyqybekvkafnkiueovlmmuevqbhxgvmxvwkgxcougqwgjipaqlefsayamrmbabkkjhikpixvsstggiwktfiiiixotssvzwzjsvbsgakdawhlzyjmgjnuyjbvpnuxatrloupoeyerlnbjkjmwrqakzndjekmavhkgxcyybvvldrepcfaovjvqkdbjvqquhyflmzdaovifajlwnvtbhgkhivnlxlubqervd",
        "dzdozvwjsaijelefqsgyapusvmpnojjbzojtienlkaqbefjeuyxkvruymgvnllmkigqafwirwkmfnndikkrvpkjebcibuvznwnmhzoiykoggauvmejiqabackahyxkafkvaegbwzvqklurmxagddjwkpwqvibhqtxxvuvshgltsddsyvxyvotbdalqscuxvitbfrbovnumhjkhiwthyaycvvqiybkupllrmgedojmxlpjqhvnokapegjvl",
        "fpykyddtjjibbakvqjdfvvknyitauoqyckkhcanehqgianrickgywikeyoabkamozpwqfnbmivnwpevbqvjuudezptxpushgglmpskvvemukkvmgzxgdfklnymrivjemlsgmydlxabnjhslqgmtuuakungzvgvxwajqyixqhiljmilkwbulbxhqpiywrofdjewadsjkbrvszsqaobzlnfxtohrhxvbukoleijvreatjcevjowalvavdovv",
        "ueevkksbxmxvdutenusguauvloqdzonkrkqyvrlaithgeluavkhpxqaaaoysrpezajvkmpdatuvqykswhvapkjnmgxvuyuxjlbwkrbfvkwlqrtepbbjzyovfkqveifajygqcinbfgdeasmzjaxibliqogbvmndhfgiakygabxdhovmghqskmyvzpuivwqknmwlihnkzojpyjsjrjvkclmwinwgjljccljoeilndtbovhdxydmwbvtvifei",
        "uqijsmtvriacoqfdlotnpbrokmkehnleqqkgeuvbvmjwpvlglvtgdkwsbiivlxxmjcraebdjswdquinzyvfkogvhfhujwmfsdlyidunpyrvqaqlvilknzvkectskiwieijpxbyfoedyaugyvmwzeqvuwakjgnbepvejnowinhzukajmaaxymgvhzovdabqgamltxtkzhklbggapvfmybjqyuhbhsobjxolxukaikxvasvvayjkpkjcnrrd",
        "wxvyqeidovwhvfscbgvylakunmtjsbnanepehfkkkvqmajaskmidphmzxpkbkgjxvtalkdsaupybtamcvrwkmrvqbkeojllrtpsigdhaqluueozjvsaajnayljqgzvbajlbknbykdzixegbnetivcrvbwaovejtfycddoynywvfouwlqkirkqeivahugyqvpziloxvgijbuudlnqymdulkkzmhohpjwrhvfnxvwfimqiuxgxigvjgoesmj",
        "riellsqyeiuqzjpapwvmpqyezartjhflvjwuqkvbfjuydbitkwypnnbksjbtjbaqiuazlewvdwbxevlndxpmlqgvmoyavavgaomyiokxuajyhagixcjdeisrvvakfsjknqehkhvkvmniwjgmevqhrnkpawlstkxfvoyudaznivhgkbbdpditucrhtqehbxiagraxuikldnzlukvxfnkkjgmlksmsgoqvdmebvjgyclboomvwvfyogojucz",
        "ojwykmncocsubpameljxceikiqoyiulqluvjxyfztkrxnmeljvonndwalggaivhbbkotliuvnbvabpvdbokesqvvgiwojyhajtniajbkzvurmskzcplyfpiayfadklqdndbgkvmhgvkupuktvmguhkljxukfojwrvqagpvzygavrlhsuyeedtzmvkqejtavbjhlazyfwewfxysqxdqimrvmnbpvhwivqseqrbxmigdskkngihwadajxeoj",
        "ivejavaxvbmvplklogyawesimhovskbhivsinnobrkhddetfamkhkdkoivxcajsgtxezatcfevjlbqwbkxidqyyyknkykujkiwvawvidjzmoouqnwrmpibrpmmwgnkbvnsjjfymdgyqlalnfvyicvboungbjmuuhfghtjbsuaqlzateyvregldevrkxlkuvboyepkvoxxcamgdfsjqtpguuqgaewlazvqrvuzzqjjhqilipwpxkhjvland",
        "hadqkesxllraekarnegwjqoduaawrpowvusqcauylyvrysnlvlkqxwkxvpvpieuvvnjvjgvjtcuqdxivozitieqdjdnexhbeaclvphlaqmkmsxxjljfbfiogkkhkjtzxyvakmnofgmhuvsyabbmpjdesmbbhkzhjbfkndmyjbkkqavjvdbfgluvivgiealimwpzqsfgoivzyjunyowievipvcuytdnlrwqoatzikbbahwrmmgngkuytgok",
        "kirckfiiujesbjkqbjthvamlvylartnaumuxjwaaqlwnrqqdvmanvbpgejxvdxyykofrhlngzkcwbquiiucovkjioboideggkqsnmkkdaggsavibwzfdmoluktpybvhgfxehuojbmjcivehnwvlsiekjeaukdvzwaeyyvpdmrjfxqawnajyoeqgiddsytvwyzpangvklvbjtkhmusovyohrvkbkhvjitvxxqpgslmlbmellpquzpnafxvz",
        "ouijmmjiteeauugfxovoguwsdlibsrjtgbkbxehkiuahrirwvjsmwwvebypvmdmalkyvkkdynvqibbwxpkclyozeeegevatukmkdbqxewlyhvinolrhbalgsapvynftlqqpxnlfkclnvhhcpxgxknajbifyqzfjukizbosntgjjuohsqhkjyujcjoavvdqvwtnglaoivamvkgasybwmupkkrkjzvjmzgfidazyqvnrxdmqaplevdqvviad",
        "dbtxpbqtbhkjgazvfiqvbmflasopmjibejdiuayizylxvrvxykqawrygjtlvshyaiwlbnuajzpzblrhigxedbmvlmveftggvhnfusveitvvvojelvznwfmuirkkbqmwakubekcxjqnfpknnoavauskueyavphcsyowqxlccdaeykptkiqdiueawvokolusqgkkvxkjbvoqdjmghnmdmjaggjwzjoykiqwravgdnmlokndjvyhiselhurxp",
        "dbtxpbqtbhkjgazvfiqvbmflasopmjibewdiuayizylxvrvxykqawrygjtlvshyaiwlbnuajzpzblrhigxedbmvlmveftggvhnfusveitvvvojelvznwfmuirkkbqmjakubekcxjqnfpknnoavauskueyavphcsyowqxlccdaeykptkiqdiueawvokolusqgkkvxkjbvoqdjmghnmdmjaggjwzjoykiqwravgdnmlokndjvyhiselhurxp",
        "ogjiviqmvgagejrvvzkokjoudnxilycihrsxvvvyeaykghpkmwtttjrsiwnekykjjbkmidvqwjfpvaouvoowoxaqywdivghqbkqyhgflvfhlpsbmvmjuhcczflqbgmneloyvnjzdxlzpnplxseticqlbxiuevkxnuikadzjgmaenzkuvjhuagqvmblybifybkawjwuqpaupshtdmeqdlbvfkektrvuagsrdnajlebbaaivnsykomxkrwad",
        "akyzdjdzztxvuduxkqklievwnfbozdxaojbdklpefiaawobamqezvqjpeuskgmrrlyaquftcgribbmkpdviamegektoblvevjrvvtnukmvwpgmvlakexynnsbahgvwobsejivgbgljhikxduxrvacqqdkpighfhkyulkkysjlgmtmsljjosihvynmcmlcaqsnhvfjbxxeqtprquvywnydkpqvkagavwjnwyfnhaziijywohjuuovlviiob",
        "ieonegohvqdijnjwziloffltzumageoynbiyureqtezkblpbdvmvbacijbwfenzdgoyvqvsyckhaoksmbkkrjmjjynskmglfvoskbwtxtaiwlkdwyabmjvhjphkuayreqhakvghmztcupximpxprqbejwxbjuhfiudwjvlsilpaegmtqvsrqanuvkvdlasvbknhrglakxiqcvvlaajfzxvkdiagnvkdqgdyqkyuuvwupoxmiejlvgxvyon",
        "cnuwisaiyygvoldafjjskyvnnxocuqkrmleibiuxdcjgvuzxthbvoyxvzpnlzmemwbmlisfyogjpelpxejbbujywekojaknwlvrahnmaieeqkdhksovshqlaiinbyvvqewguatoapfqklkbhyvtwvknjudkqjodfktsvmajbfbxkvgmqvkheljvwurrldgzampamdgawzvkvbnfibqojeiazlvqtkgpyygvgushkuxhcpdqjdraiirtmxv",
        "rabsbjkkutonymdmwlidwviymobvrvhkgvvejuqaroliatyktheuqviohkkcboznpnubnwkltbuzjfxvzjcjxspovpdkgkppxtdumbnapvnyeykqhqhglkcveqfshkhlglvevnzcmygdxjgavunweaiixvyjvqfkmvedvjlmxqjrumfjxjxoksvbvququbaanzdawqjodaeylratyzpissblfwiamkvgliwgigeigaiabwofeklhsydjmr",
        "jxogakoubegqvlcdrmyikhizvevujigkqvlhmundekpoikwebglllmnwwkabyalsjvxpnugwdsfvqahmmuiyaazrmelnqyelevlnqvjvgkvgcovjewghaxoshrmbaytltiehqnjsmxjpxctklxjkkoxfwpbikqpzrvaguhrzamumvdbfbikcvzodhfvyyugtjznisiiuqovxbnuryvjnkidytkjvpvbeatwbkssdbydkdavjfpqqawajof",
        "ieonegohvqdijnjwziloffltzumageoynbiyureqtezkblpbdvmvbacijbwfenzdgoyvqvsyckhaoksmbkkrjmjjynskmglfvoskbwtxbaiwlkdwyatmjvhjphkuayreqhakvghmztcupximpxprqbejwxbjuhfiudwjvlsilpaegmtqvsrqanuvkvdlasvbknhrglakxiqcvvlaajfzxvkdiagnvkdqgdyqkyuuvwupoxmiejlvgxvyon",
        "xokkxyljivqbbiygkgmfndwvxuqblyamlwqosoqdrbeszrebkimgyvqytcdrvjkoiyrwvixeilstggjtvfvkbkmjkwlknkapumlhdzcvzhjzeaiigahhvasawhuqikeubavfnpbaoilorukmpftxeadfjjvpazxkacthvgvxxynjjravlidcjsousbzewmpqgehlvounvvpyvvieushqgfelnvlgumaajdbmounnwqkdwtqyjkdkpynmjb",
        "uqijsmtvriacoqfdlotnpbrokmkehnleqqkgeuvkvmjwpvlglvtgdkwsbiivlxxmjcraebdjswdquinzyvfkogvhfhujwmfsdlyidunpyrvqaqlvilknzvkectskiwieijpxbyfoedyaugyvmwzeqvuwakjgnbepvejnowinhzukajmaaxymgvhzovdabqgamltxtkzhklbggapvfmybjqyuhbhsobjxolxubaikxvasvvayjkpkjcnrrd",
        "ogjiviqmvgkgejrvvzkokjoudnxilycihrsxvvvyeaykghpkmwtttjrsiwnekykjjbkmidvqwjfpvaouvoowoxaqywdivghqbkqyhgflvfhlpsbmvmjuhcczflqbgmneloyvnjzdxlzpnplxseticqlbxiuevkxnuikadzjgmaenzkuvjhuagqvmblybifybkawjwuqpaupshtdmeqdlbvfkektrvuagsrdnajlebbaaivnsykomxarwad",
        "xnvkvtideprgzhqgbyzaobfqkkzkykawzssheivkukpugmamjgqkeffmyvjxlcatwxkhvvaskdnqvvjkginkaauihwtvpaiipdnugxboyjsljmngbxioryliaglqquukerywwboirwfhejyfmorsybbdaxagclnoobvlmmkjhnjwpivbmxynnfeuluvdevsuvjvilvdzavekjvxyvwrqltdjjtjlqmcbhqboieaqpukpsacoddtzvlemhg",
        "olwrmjdvzgnsinneshaqfwqbmqezrmbvvykbdqqegntsxoyyktwbxnbqvbhaubkmgtkjqjugkaelribjeaxaciepkmbfdhjqmvnlevykdsnrvujluvaxyykuphoyoakmaxwobzpivilvtoifealvanjovtgkjlqjswrjpvfvhkvilkrtmwikigpmdkiogzqygycigaxvdvzxxpadudnudylujjhmhfkclcavavpvswjlubeioukwfhgesz",
        "riellsqyeiuqzjpapwvmpqyezartjhflvjwuqkvbfjuydbitkwypnnbksjbtjbaqiuazlewvdwbxevlndxpilqgvmoyavavgaomyiokxuajyhagixcjdezsrvvakfsjknqehkhvkvmnmwjgmevqhrnkpawlstkxfvoyudainivhgkbbdpditucrhtqehbxiagraxuikldnzlukvxfnkkjgmlksmsgoqvdmebvjgyclboomvwvfyogojucz",
        "byvhyvyungwwwycoeunjojnjliifvxqqrkvgksidmsedjkzaxiekxwwluqjkuhcavldovgakvtvfjfakcxdwjpgdvymtmhojaahaomkytkebxsbpaquujxnfvevhmgmklagtmzrvekalhqeknjivssqbweifzxatvxvgqqikvjiphlbkzqjkvvgibyntvnmdujgprvfgoesrpmldsprnbzbldqyzobirbkaunpdmuleooiawcyuillhaby",
        "dbtxpbqtbhkjgazvfiqvbmflasopmjibejdiuayizylxvrvxykqawrygjtlvshyaiwlbnuajzpzblrhigxedbmvlmveftggvhnfusveitvvvojelvznwfmuirkkbqmwakubekcxjqnfpknnoavauskueyavphcsyowqxlccdaeykptkiqdiueawvokolnsqgkkvxkjbvoqdjmghnmdmjaggjwzjoykiqwravgdnmlokudjvyhiselhurxp",
        "ogjiviqmvgagejrvvzkokjoudnxilycihrsxvvvyeaykghpkmwtttjrsiwnekykjjbkmidvqwjfxvaouvoowoxaqywdivghqbkqyhgflvfhlpsbmvmjuhcczflqbgmneloyvnjzdxlzpnplxseticqlbxiuevkxnuikadzjgmaenzkuvjhuagqvmblybifybkawjwuqpaupshtdmeqdlbvfkektrvuagsrdnajlebbaaivnsykompkrwad",
        "tektvgygkafuuybalsmvkubguhmaqqjmhjxivxuawlzokebamyucpqambqlswddoqyilhyasdimjnejwbvknaiytuklooqxmbvvwvzklpjizumgdwkmvvneoqgajhacwaxsbvzovhjxjfwirtdejynsfklarbhvkgpvizrrielyveklmnhvputqvipxaqfkbkeduboltjgvnbypvjrprjsvvlnedcidywggghfxnzsoeonkijxcikkdafq",
        "wxvyqeidovwhvfscbgvylakunmtjsbnanepehfkkkvqmajaskmidphmzxpkbkgjxvtalkdsaupybtamcvrwkmrvqbkeojllrtpsigdhaqluueozjvsaajnayljqgzvbajlbknbykdzixegbnetivcrvbwayvejtfycddoynowvfouwlqkirkqeivahugyqvpziloxvgijbuudlnqymdulkkzmhohpjwrhvfnxvwfimqiuxgxigvjgoesmj",
        "ueevkksbxmxvdutenusguauvloqdzonkrkqyvrlaithgeluavkhpxqaaaoysrpezajvkmpdatuvqyksmhvapkjnmgxvuyuxjlbwkrbfvkwlqrtepbbjzyovfkqvmifajygqcinbfgdeasmzjaxibliqogbvwndhfgiakygabxdhovmghqskmyvzpuivwqknmwlihnkzojpyjsjrjvkclewinwgjljccljoeilndtbovhdxydmwbvtvifei",
        "ikaiaihivqfvwqixouhzwkaidlvksgyhdnrlzyvbqzabwuvjelpnakqnevkuaalejyhbymsxlsnpqxynvvlhhikqctrswduvmvfqjmmyhoaoxwpiaqdueklgsdosnbvkbmjdmcawfregiuikbvbfjokjylkugqjxesgjigvpvwouggajtlobrviennmxkpdoreftkokvxhjbyemlakwjgmgavdvrtbztcdbyvvzujxtzcepnfjmyalkupq",
        "wdjbpfcewhuvjfqdyqeomfptuqxdtjiwwryjalbitkijkhkajglxgawkvesuydghfzxzirzgydyabooitxobgldmsfchxinipvaessorcxayxbdvvhnouqtkvbuyneywdhldhvkqsuwingpugklemgmvacrkekvpvnaulablvaumaabjvrevjovvrjtlvmifxnyneapwupvjnkmibzqvhkqbqykzavqlgkbqvljizesokmsjlmmoknjigk",
        "mxsoakouqvnkljjnwmfhgrvoiqywsenlylepvzftaetslggakoeokkuxviicwhpbgijnlmddqehdeipbvxmhkymgvdlrvbkuvjgibbbibgfpnqabmwjolbwitfxazdhujmkvgmnunzxlvmkxpedukohwyevdijsjjodfrcyukqylwkqjevsbvzrrzviaqnuvyqsxgvvhjhgkaycvteqliaukaasmajqrxykatiwcolptpjabvykfauznvd",
        "gvmooiuektkrevaxmiwbjaojashkbbmaglbmayhvqnvtwnydcvjgyppuuklvejqjrcbyzviabemqqntijvyglvxpjvkieuaydvgzzljvubfasavxxwvaugyomwpxjubksqkaveqdzrsvaxuwkdkdiqgxmnhwwpliabdondvjvflmsykljmeluhhbhtkegizqvhilkcomnpnqrkriufiwydjkfghgofnvcbjlfltyasrsqeodikokepxnzt",
        "xnvkvtideprgzhqgbyzaobfqkkzkykawzssheivkukpugmamjgqkeffmyvjxlcatwxkhvvaskdnqhvjkginkaauihwtvpaiipdnugxboyjsljmngbxioryliaglqquukerywwboirwfhejyfmorsybbdaxagclnoobvlmmkjhnjwpivbmxynnfeuluvdevsuvjvilvdzavekjvxyvwrqltdjjtjlqmcbhqboieaqpukpsacoddtzvlemvg",
        "fmjfhjgqitfbarfmehsgdgzmjkidukgkdobakbqybwqvohgshzbcemvwkvvqaitexovbjehlynuvvqeeqskswjrkmbwxmvualkfvbljgvxahkxnulikkkqirnpdupamhalpmwaodvxyejadvujsiriqglaagdaiyymailmjpfzvovnvyoosdllnwkjqglweyvrrhvestvpowccubnnxujjyxnqkuaicbbvzxkiiztpduvketljpyogyznt",
        "djpeuvljthgqtuubiyvwoewgkjaevcmyurkubmcfxfakqwdueadtcvmajizpikvsmbvvihtosovzqxivqijsjndvayvkrgniqzpbamyjjanykktusjxjayonvygbahwjdsyshfzjlxwevxlnpwezlurokpbklgviioxszhvkmngqvgaxlfkokkxpbymarkeloolnabelmfrvdgaarkghypvbcdbvekmnifmuqlhdvjditiqbewhlqwnuqg",
        "nbqdjymukphaefwnymugyovgauqixvwymjbjvkgninvcbvvxosjlmwmzdivwtfoydlgypilkwbgkaclyuviekhevidoolwbpveejxkqqsjeggisgkunvjkbmrlgthnofsqlvvpsaxopbltikaseruricezkmwazvfnqqvvgzfnsnaajdydduavozifjbbvxhdahylchjuxepjmxlujdrupwtkbibkyjxqkrlaraohhemzkktqkatmqviav",
        "pefbijvvskonrajtmqwguektpjluvyykdvgjmakhoyeqweyfvbxhfvalsvkxgupwudlqlrnivtnztilxndvgrkyawkndloeypsmkjpdollmsikkmkuvjjzlagregagkxecvfhiygjdbhhmafxjiobmpaimvvobmeebykjekvqwauaqbvwtldsbisolbvwhqrziojvqzxvnoidqbaungrhmnqyicbjkaaatzjvygdcuipnqusfuxczwvxkh",
        "arksvpqntqboagupaduhgjmqrvqgesljktgxllciygmlzqbuatoxrvjeajvybiznvvyvhajfvkclqvpnezijaocwooykbwnzkpikqhmnmadgilvvhnwyjyujjqgakfkwkxrdvuasswoleutoklgmfrixiypumlkwidlypkgepavvnkqbxsbwxsmznrtomcubyjiheblvkbnedeovfuvhkhvuqffdmiaixydevzkjgtbjdjvamwbeshadxi",
        "sbeilghalvxbygvnpihgotwmyrxvgbhnlnqmkmsbavhaoivvnvdjqqvrueykjyktpwiiyuidqyxmuiwdcrjeizljekrhldfiapvzmopfekuokldbzxgvucvjnrynolhfdkxmgwpojcvtatalegfkgcgvakmqsamuwfqbovzyxjnevtbjsqioabljdujdwjvhvehkdksnemgskavafbuqvkseaqipbxkzlauijwwktqyzrjvykloaxupbnm",
        "sobuexbmbiaxqmvviodjbjvpxkfvxnjejsvsdbnyktlakcutkynieokevehopvfgtlyzgwbayskqzvxhbaejlvvwlmrvkidxrnbybdandjyrjqndqvdsgainzgrqzsaeweflpjokhugujwavuuijwtfitfoyprmmwqtogahulsgommnvjyhraplkkvaqgdkeamzupkifavqvhiyakjpxhnkqikyquvzlovvwidcmlhbejgclxiuglmcbkw",
        "riellsqyeiuqzjpapwvmpqyezartjhflvjwuqkvbfjuydbitkwypnnbksjbtjbaqiuazlewvdwbxevlndxpmlqgvmoyavavgaomyiokxuajyhagixcjdeisrvvakfsjknqehkhvkvmniwjgmevqhrnkpawlstkxfvoyudaznichgkbbdpditucrhtqehbxiagraxuikldnzlukvxfnkkjgmlksmsgoqvdmebvjgyclboomvwvfyogojuvz",
        "xokkxyljivqbbiygkgmfndwvxuqblyamlwqosoqdrbeszrebkimgyvqytcdrvjkoiyrwvixeilstggjtvfvkbkmjkwlknkapumlhdzcvzhjzeaiigahhvasawhuqikeubavfnpbaoilorukmpfqxeadfjjvpazxkacthvgvxxynjjravlidcjsousbzewmpqgehlvounvvpyvvieushqgfelnvlgumaajdbmounnwqkdwttyjkdkpynmjb"
    ]

    tic = time.time()
    ret = Solution().numSimilarGroups(A)
    toc = time.time()

    print(f"Found {ret} similar groups in {toc-tic:.3f}s.")